/*

 LEVEL3MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : levelTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level3MapWidth 20
#define level3MapHeight 18
#define level3MapBank 0

extern unsigned char level3Map[];

/* End of LEVEL3MAP.H */
