/*

 LEVEL5MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : levelTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level5MapWidth 20
#define level5MapHeight 18
#define level5MapBank 0

extern unsigned char level5Map[];

/* End of LEVEL5MAP.H */
