/*

 LEVEL1MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 32 x 32
   Tile set      : level1Tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level1MapWidth 32
#define level1MapHeight 32
#define level1MapBank 0

extern unsigned char level1Map[];

/* End of LEVEL1MAP.H */
