/*

 LEVEL4MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : levelTiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define level4MapWidth 20
#define level4MapHeight 18
#define level4MapBank 0

extern unsigned char level4Map[];

/* End of LEVEL4MAP.H */
